version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.0
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - composer install
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building Laravel...
      - docker-compose build app
      - echo Building React...
      - docker-compose build frontend
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
