name: Deploy to EC2

on:
  push:
    branches:
      - main # Change this to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 3.142.248.73 # Or use the DNS name
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/vetjacket  # Navigate to your app directory
            git pull origin main  # Pull the latest code
            # Add any additional deployment commands here
